import React, {useEffect, useState} from "react";
import {
    FlatList,
    Image,
    ScrollView,
    StatusBar,
    StyleSheet,
    Text,
    TextInput,
    TouchableOpacity,
    View
} from "react-native";
import {Feather} from "@expo/vector-icons";

const Home = ({navigation}) => {
    const [plantName, setPlantName] = useState('');
    const [plant,setPlants] = useState([]);
    const [filteredPlants,setFilteredPlants] = useState([]);
    const plants = [
        {
            id: "1",
            name: "Beans",
            image: require('../assets/vegetables/1_BEANS.png'),
            batonical : "Phaseolus vulgaris\n",
            nutrients : "1.5 g of protein,16.6 g of fiber and 4.56 mg of iron in 40 g pf beans\n",
            soil : "slightly acidic to neutral,ph between 6 to 7\n",
            water : "about 1 to 1 1/2 inches per week. (75-100 gals. / 100 sq. ft.)\n",
            temp : "65 to 85 degrees F\n",
            mois : "17%\n",
            practical : "75 to 200 mm or 3 to 8 inches\n",
        },
        {
            id: "2",
            name: "Broccoli",
            image: require('../assets/vegetables/2_BROCCOL.png'),
            batonical : "Brassica oleracea\n",
            nutrients : "fiber, vitamin C and K, iron, potassium\n",
            soil : "sandy loam to clay loam\n",
            water : "One to two inches of water per week is recommended for broccoli, depending on the weather.\n",
            temp : "60 to 65 degrees F \n",
            mois : "82.87%\n",
            practical : "15 cm\n",
        },{
            id: "3",
            name: "Cabbage",
            image: require('../assets/vegetables/3_CABBAGE.png'),
            batonical : "Brassica oleracea\n",
            nutrients : "22 calories, sugar, protein \n",
            soil : "medium to heavy loam\n",
            water : "1 to 1.5 inches per week.\n",
            temp : "40 TO 80 Degrees F\n",
            mois : "92%\n",
            practical : "40 to 60 cm\n",
        },{
            id: "4",
            name: "Carrots",
            image: require('../assets/vegetables/4_CARROTS.png'),
            batonical : "Daucus carota\n",
            nutrients : "potassium, antioxidants, and vitamin A \n",
            soil : "loose,well drained soil\n",
            water : "one inch of water per week 65 gals./100 sq. ft.\n",
            temp : "40 to 80 degrees F \n",
            mois : "89%\n",
            practical : "15 cm\n",
        },
        {
            id: "5",
            name: "Cauliflower",
            image: require('../assets/vegetables/5_CAULIFLOWER.png'),
            batonical : "Brassica oleracea\n",
            nutrients : "77% vitamin C, 20% vitamin K, 10% vitamin B6\n",
            soil : "fertile soil with ph 6 to 7\n",
            water : "1 inch (2.5 cm) of water per week.\n",
            temp : "60 TO 65 Degrees F \n",
            mois : "94%\n",
            practical : "13 to 20 cm\n",
        },
        {
            id: "6",
            name: "Cucumber",
            image: require('../assets/vegetables/6_CUCUMBER.png'),
            batonical : "Cucumis sativus\n",
            nutrients : "4% potassium, 3% fiber, 4% vitamin C\n",
            soil : "loose,organic matter\n",
            water : "about 1 to 2 inches of water per week, depending on the soil and weather conditions. More water may be needed in hot, dry weather\n",
            temp : "75 to 85 degrees F\n",
            mois : "97%\n",
            practical : "62 cm\n",
        },
        {
            id: "7",
            name: "Green Beans",
            image: require('../assets/vegetables/7_GREEN_BEANS.png'),
            batonical : "Phaseolus vulgaris\n",
            nutrients : "High vitamin K\n",
            soil : "sightly acidic to neutral soil\n",
            water : " about 2 inches per square foot per week.\n",
            temp : "65 to 85 degrees F\n",
            mois : "55%\n",
            practical : "4 inches\n",
        },
        {
            id: "8",
            name: "Leafy Greens",
            image: require('../assets/vegetables/8_LEAFY_GREENS.png'),
            batonical : "Brassica oleracea\n",
            nutrients : "Rich in fiber, low in lipids, rich in folate, ascorbic acid, vitamin k, Mg \n",
            soil : "loose,rich, and well drained\n",
            water : "1-2 inches of water per week\n",
            temp : "70 to 75 degrees F \n",
            mois : "94.70%\n",
            practical : "6 to 7 cm\n",
        },
        {
            id: "9",
            name: "Lettuce",
            image: require('../assets/vegetables/9_LETTUCE.png'),
            batonical : "Lactuca sativa\n",
            nutrients : "nitrogen, phosphorous and potassium\n",
            soil : "deep black sandy loam\n",
            water : "1 inch of water per week\n",
            temp : "60 to 65 degrees F \n",
            mois : "91.85%\n",
            practical : "8cm\n",
        },
        {
            id: "10",
            name: "Peppers",
            image: require('../assets/vegetables/10_PEPPERS.png'),
            batonical : "Capsicum annuum\n",
            nutrients : "vitamin A, C, potassium, folic acid, fiber\n",
            soil : "rich'loamy soil\n",
            water : "I inch of water per week and for every square foot, use one gallon\n",
            temp : "70 to 80 dwgrees F during day\n",
            mois : "94.13%\n",
            practical : "6 to 8 cm\n",
        },
        {
            id: "11",
            name: "Peas",
            image: require('../assets/vegetables/11_PEAS.png'),
            batonical : "Pisum sativum\n",
            nutrients : "vitamin C and E, Zinc, antioxidants\n",
            soil : "sandy to heavy clay\n",
            water : "about 1 inch of water per week in 65 gallons per square foot\n",
            temp : "55 to 65 degrees F \n",
            mois : "18%\n",
            practical : "10 to 20 cm\n",
        },
        {
            id: "12",
            name: "Summer Squash and Zucchini",
            image: require('../assets/vegetables/12_SUMMER_SQUASH_AND_ZUCCHINI.png'),
            batonical : "Cucurbita pepo\n",
            nutrients : "vitamin C, folate, beta carotene, calcium, zinc, iron, potassium, magnesium\n",
            soil : "rich fertile soil\n",
            water : "1-2 inches of water per week\n",
            temp : "65 to 75 degrees F \n",
            mois : "95%\n",
            practical : "6.4cm\n",
        },
        {
            id: "13",
            name: "Sweet Corn",
            image: require('../assets/vegetables/13_SWEET_CORN.png'),
            batonical : "Zea mays\n",
            nutrients : "17% of daily calcium\n",
            soil : "well drained soil suppliedwith organic matter\n",
            water : "1 inch of water per week\n",
            temp : "70 to 86 degrees F \n",
            mois : "17.06%\n",
            practical : "10 to 25 cm\n",
        },
        {
            id: "14",
            name: "Tomatoes",
            image: require('../assets/vegetables/14_Tomato.png'),
            batonical : "Solanum lycopersicum\n",
            nutrients : "calcium, vitamin K, lycopene\n",
            soil : "fertile loam with ph 5.8 to7.0\n",
            water : "an inch per week\n",
            temp : "55 to 85 degrees F\n",
            mois : "90%\n",
            practical : "4 cm\n",
        },
        {
            id: "15",
            name: "Winter Squash",
            image: require('../assets/vegetables/15_Winter_Squash.png'),
            batonical : "Cucurbita maxima\n",
            nutrients : "vitamin C, folate, beta carotene\n",
            soil : "soil with ph 6 to 6.5\n",
            water : "1-2 inches per week\n",
            temp : "50 to 90 F\n",
            mois : "81%\n",
            practical : "11.65 cm\n",
        },
        {
            id: "16",
            name: "Daylily",
            image: require('../assets/vegetables/16-daylily.png'),
            batonical : "Hemerocallis citrina\n",
            nutrients : "protein, vitamin C\n",
            soil : "rich,well drained and aeration\n",
            water : "1 inch of water per week in 65 gallons./ 100 sq. ft. \n",
            temp : "Minus 25 F\n",
            mois : "60%\n",
            practical : "2 to 8 inches\n",
        },
        {
            id: "17",
            name: "Hosta",
            image: require('../assets/vegetables/017._HOSTA.png'),
            batonical : "Hosta spp\n",
            nutrients : "calcium, magnesium, copper\n",
            soil : "fertile soil imcluding heavy clay\n",
            water : "1-2 inches of water per week\n",
            temp : "33 to 41 F\n",
            mois : "75%\n",
            practical : "1 to 2 feet\n",
        },
        {
            id: "18",
            name: "Hibiscus",
            image: require('../assets/vegetables/018._HIBISCUS.png'),
            batonical : "Hibiscus spp\n",
            nutrients : "magnesium, manganese, iron, copper\n",
            soil : "well drained with organic matter\n",
            water : "1 inch of water per week in 65 gallons./ 100 sq. ft.\n",
            temp : "60 to 85 F\n",
            mois : "89.34%\n",
            practical : "2 feet\n",
        },
        {
            id: "19",
            name: "Coral Bells",
            image: require('../assets/vegetables/019._CORAL_BELLS.png'),
            batonical : "Heuchera sanguinea\n",
            nutrients : "copper,calcium,magnesium\n",
            soil : "rich well drained soil \n",
            water : "what are the watering recommendations for coral bells\n",
            temp : "15 to 18 C\n",
            mois : "45%\n",
            practical : "2 to 3cm\n",
        },
        {
            id: "20",
            name: "Catmint",
            image: require('../assets/vegetables/020._CATMINT.png'),
            batonical : "Nepeta cataria\n",
            nutrients : "nutrients contain minerals that are benefical for digestive system\n",
            soil : "Well drained soil\n",
            water : "1 inch per week\n",
            temp : "55 to 85 F\n",
            mois : "40%\n",
            practical : "24 inches\n",
        },
        {
            id: "21",
            name: "Ornamental Grass",
            image: require('../assets/vegetables/021._ornamental_grass.png'),
            batonical : "Poa annua\n",
            nutrients : "potassium, fiber\n",
            soil : "Slightly moist and well drained\n",
            water : "an inch of water per week\n",
            temp : "60 to 68 C\n",
            mois : "60%\n",
            practical : "tall grass\n",
        },
        {
            id: "22",
            name: "Russian Sage",
            image: require('../assets/vegetables/022._RUSSIAN_SAGE.png'),
            batonical : "Perovskia atriplicifolia\n",
            nutrients : "highly nutrients rich herb\n",
            soil : "average to lean soil with a slightly alkaline ph \n",
            water : "1 inch of water per week in 65 gallons./ 100 sq. ft. \n",
            temp : "Minus 20 to minus 10\n",
            mois : "33%\n",
            practical : "2 feet\n",
        },
        {
            id: "23",
            name: "Salvia",
            image: require('../assets/vegetables/023._SALVIA.png'),
            batonical : "Salvia officinalis\n",
            nutrients : "vitamin C, E and carotenoids\n",
            soil : "well drained soil\n",
            water : "1 inch of water every 7-10 days\n",
            temp : "32 F\n",
            mois : "7%\n",
            practical : "2 mm\n",
        },
        {
            id: "24",
            name: "Spike Speedwell",
            image: require('../assets/vegetables/024._SPIKE_SPEEDWELL.png'),
            batonical : "Veronica spicata\n",
            nutrients : "potassium, znic\n",
            soil : "loamy \n",
            water : "1 inch of water per week in 65 gallons. 100 sq. ft.\n",
            temp : "15 to 25 F\n",
            mois : "23%\n",
            practical : "15 cm\n",
        },
        {
            id: "25",
            name: "Dianthus Pinks",
            image: require('../assets/vegetables/025._DIANTHUS_PINKS.png'),
            batonical : "Dianthus caryophyllus\n",
            nutrients : "potassium, copper, molybdenum\n",
            soil : "neutral and alkaline soil\n",
            water : "one inch of water once a week\n",
            temp : "33 to 5o F \n",
            mois : "89%\n",
            practical : "",
        },
        {
            id: "26",
            name: "Ornamental Onion",
            image: require('../assets/vegetables/026._ORNAMENTAL_ONION.png'),
            batonical : "Allium cepa\n",
            nutrients : "fat,fiber,carbohydrates,sugar,protein\n",
            soil : "well drained,sandy to stony soil\n",
            water : "1 inch of water per week in 65 gallons. 100 sq. ft.\n",
            temp : "40 to 70 F\n",
            mois : "46%\n",
            practical : "1 to 4 feet \n",
        },
        {
            id: "27",
            name: "Lavender",
            image: require('../assets/vegetables/27_lavender.png'),
            batonical : "Lavandula angustifolia\n",
            nutrients : "phytochemicals and antioxidants\n",
            soil : "fertile including chalky and alkaline soil\n",
            water : "once every two weeks during the growing season with around 35 ounces of water (1 litre)\n",
            temp : "68 to 86 F \n",
            mois : "6%\n",
            practical : "12 inches\n",
        },
        {
            id: "28",
            name: "Stonecrop",
            image: require('../assets/vegetables/027._STONECROP_1.png'),
            batonical : "Sedum spectabile\n",
            nutrients : "herb with medical importance\n",
            soil : "drained soil \n",
            water : "0.8 cups of water every 12 days when it doesn't get direct sunlight and is potted in a 5.0\" pot.\n",
            temp : "up to minu 30 F \n",
            mois : "67%\n",
            practical : "18 cm tall\n",
        },
        {
            id: "29",
            name: "Shasta Daisy",
            image: require('../assets/vegetables/028._SHASTA_DAISY.png'),
            batonical : "Leucanthemum maximum\n",
            nutrients : "contain 35 g of vitamin C per 100 g \n",
            soil : "loamy,moist but well drained\n",
            water : "1 to 2 inches per week\n",
            temp : "hardy down to minus 20 F\n",
            mois : "5%\n",
            practical : "1 to 2 feet\n",
        },
        {
            id: "30",
            name: "False Indigo",
            image: require('../assets/vegetables/029._FALSE_INDIGO.png'),
            batonical : "Baptisia australis\n",
            nutrients : "nitrogen, ammonia, nitrates\n",
            soil : "well drained\n",
            water : " 1 inch of water every couple of weeks.\n",
            temp : "21 to 24 C\n",
            mois : "3%\n",
            practical : "3 to 4 feet\n",
        },
        {
            id: "31",
            name: "Tickseed",
            image: require('../assets/vegetables/030._TICKSEED.png'),
            batonical : "Coreopsis\n",
            nutrients : "nitrogen and phosphorus\n",
            soil : "sandy and loamy soil\n",
            water : "applying 1 inch of water per week in 65 gallons.\n",
            temp : "50 to 55 F night and 70 to 75 day \n",
            mois : "8%\n",
            practical : "1 foot \n",
        },
        {
            id: "32",
            name: "Coneflower",
            image: require('../assets/vegetables/031._CONEFLOWER.png'),
            batonical : "Echinacea\n",
            nutrients : "phenolic acid, alkamides\n",
            soil : "sandy,rocky and clay soil\n",
            water : "1 inch of water per week \n",
            temp : "65 to 75 F\n",
            mois : "3%\n",
            practical : "2 to 5 feet\n",
        },
        {
            id: "33",
            name: "Croton",
            image: require('../assets/vegetables/33-Croton.png'),
            batonical : "Codiaeum variegatum\n",
            nutrients : "crude protein, crude fiber, crude fat, ash, carbohydrates\n",
            soil : "rich with organic matter\n",
            water : "1 inch of water per week \n",
            temp : "80 F\n",
            mois : "80%\n",
            practical : "10 feet\n",
        },
        {
            id: "34",
            name: "Lemon Lime Dracaena",
            image: require('../assets/vegetables/34Lemon_Lime.png'),
            batonical : "Dracaena fragrans 'Limelight'\n",
            nutrients : "calcium, potassium, vitamin C, folate\n",
            soil : "light loam with drained soil\n",
            water : "1 inch of water per week \n",
            temp : "60 to 75 F\n",
            mois : "50%\n",
            practical : "3 to 4 cm\n",
        },
        {
            id: "35",
            name: "Moth Orchid",
            image: require('../assets/vegetables/36._MOTH_ORCHID.png'),
            batonical : "Phalaenopsis hybrid\n",
            nutrients : "nitrogen, phosphorous, potassium, calcium\n",
            soil : "do noy required soil medium\n",
            water : " a splash of water to the moss once every seven to 10 days.\n",
            temp : "70 to 80 F day and 60 to 70 F night\n",
            mois : "60%\n",
            practical : "12 to 14 feet\n",
        },
        {
            id: "36",
            name: "Anthurium",
            image: require('../assets/vegetables/38.ANTHURIUM.png'),
            batonical : "Anthurium andraeanum\n",
            nutrients : "potassum, calcium, nitrogen, magnesium, iron, copper\n",
            soil : "coarse,well draining potting mix\n",
            water : "1 inch of water per week \n",
            temp : "78 TO 90  F day and 70 to 75 F night\n",
            mois : "50%\n",
            practical : "2 to 3 feet\n",
        },
        {
            id: "37",
            name: "Golden Pothos",
            image: require('../assets/vegetables/38._GOLDEN_POTHOS.png'),
            batonical : "Epipremnum aureum\n",
            nutrients : "nitrogen, phosphorous, potassium, sulfur, calcium\n",
            soil : "soilless mix\n",
            water : "1 inch of water once every week in warmer months and once every two weeks in colder months. \n",
            temp : "60 to 85 F \n",
            mois : "40%\n",
            practical : "3 to 10 feet\n",
        },
        {
            id: "38",
            name: "Lucky Bamboo",
            image: require('../assets/vegetables/39._LUCKY_BAMBOO.png'),
            batonical : "Dracaena sanderiana\n",
            nutrients : "Zn, Mn, Cu, B, Fe, and Mo\n",
            soil : "sandy loam to clay loam\n",
            water : "1 inch per week in a 65 gallon / 100 sq. ft. area.\n",
            temp : "65 to 95 F\n",
            mois : "6%\n",
            practical : "4 feet\n",
        },
        {
            id: "39",
            name: "Dracaena Marginata",
            image: require('../assets/vegetables/40._DRACAENA_MARGINATA.png'),
            batonical : "Dracaena marginata\n",
            nutrients : "good for air purification\n",
            soil : "loose,organic soil\n",
            water : "about once a week, using about 1 gallon of water per 100 square feet of plant\n",
            temp : "60 to 80 F\n",
            mois : "80%\n",
            practical : "6 to 20 feet\n",
        },
        {
            id: "40",
            name: "Snake Plant",
            image: require('../assets/vegetables/41._SNAKE_PLANT.png'),
            batonical : "Sansevieria trifasciata\n",
            nutrients : "protein,fat,fiber,carbohydrates,minerals,vitamin Aand E\n",
            soil : "light loamy soil\n",
            water : "0.5 inches of water per week in 100 sq. ft.\n",
            temp : "60 to 75 F \n",
            mois : "40%\n",
            practical : "15 inches\n",
        },
        {
            id: "41",
            name: "Peace Lily",
            image: require('../assets/vegetables/41peace.png'),
            batonical : "Spathiphyllum wallisii\n",
            nutrients : "Filter indoor air ,potassium,nitrogen\n",
            soil : "perlite,peat moss,coir or loam\n",
            water : " A smaller 8 to 12-inch tall plant will need about a quart of water for this to occur, while larger plants may need half a gallon or more per week\n",
            temp : "68 to 85 F\n",
            mois : "50%\n",
            practical : "2 to 3 feet\n",
        },
        {
            id: "42",
            name: "Ponytail Palm",
            image: require('../assets/vegetables/43._PONYTAIL_PALM.png'),
            batonical : "Beaucarnea recurvata\n",
            nutrients : "calcium,potassium,folate\n",
            soil : "fast draining soil\n",
            water : "1-2 inches every 7-10 days\n",
            temp : "60 to 85 F \n",
            mois : "30%\n",
            practical : "30 feet\n",
        },
        {
            id: "43",
            name: "Majesty Palm",
            image: require('../assets/vegetables/44._MAJESTY_PALM.png'),
            batonical : "Ravenea rivularis\n",
            nutrients : "contain oil,lumber \n",
            soil : "loamy soil\n",
            water : "1 to 1.5 inches of water per week\n",
            temp : "65 to 75 F\n",
            mois : "4%\n",
            practical : "15 to 20 feet\n",
        },
        {
            id: "44",
            name: "Peacock Plant or Calathea",
            image: require('../assets/vegetables/45._PEACOCK_PLANT_OR_CALATHEA.png'),
            batonical : "Calathea makoyana\n",
            nutrients : "ornamental plant\n",
            soil : "mixture of peat,sand,perlite\n",
            water : "1-2 inches of water per week\n",
            temp : "65 to 75 F\n",
            mois : "60%\n",
            practical : "4 feet\n",
        },
        {
            id: "45",
            name: "Bromeliads",
            image: require('../assets/vegetables/45Bromeliads.png'),
            batonical : "Bromeliaceae\n",
            nutrients : "nitrogen,phoshorous,K,Ca,Mg,S\n",
            soil : "fast draining soil\n",
            water : "is 1-2 inches of water per week\n",
            temp : "70 to 90 F\n",
            mois : "60%\n",
            practical : "2 to 3 inches\n",
        },
        {
            id: "46",
            name: "Aloe Vera",
            image: require('../assets/vegetables/46Aloevera.png'),
            batonical : "Aloe barbadensis\n",
            nutrients : "Vitamins,enzymes,minerals,sugar,lignin,saponins,salicyclic acids and amino acids\n",
            soil : "well draining potting mix\n",
            water : "1 to 2 inches in 2 to 3 weeks\n",
            temp : "55  to 80 F\n",
            mois : "97.80%\n",
            practical : "60 to 100 cm\n",
        },
        {
            id: "47",
            name: "Jade Plant",
            image: require('../assets/vegetables/jade.png'),
            batonical : "Crassula ovata\n",
            nutrients : "NPK nitrogen ,phosphorous,potassium\n",
            soil : "loose,rocky soil\n",
            water : "1 to 2 inches  once every 2 to 3 weeks\n",
            temp : "65 to 75 F\n",
            mois : "50%\n",
            practical : "5 foot tall\n",
        },
        {
            id: "48",
            name: "Blueberries",
            image: require('../assets/vegetables/blueberies.png'),
            batonical : "Vaccinium corymbosum\n",
            nutrients : "protein,fat,fiver,carbohydrates,sugar\n",
            soil : "acidic soil with ph 4.2 to 4.6\n",
            water : "1-2 inches of water per week\n",
            temp : ">32 °C\n",
            mois : "84%\n",
            practical : "0.2–0.6 inche\n",
        },
        {
            id: "49",
            name: "Radishes",
            image: require('../assets/vegetables/radishes-1.png'),
            batonical : "Raphanus sativus\n",
            nutrients : "protein,fiber,carbohydrates,sugar,fat,cholestrol\n",
            soil : "sandy\n",
            water : "1 inch of water per week\n",
            temp : "40 to 70 F\n",
            mois : "6.00%\n",
            practical : "2cm diameter\n",
        },
        {
            id: "50",
            name: "Coffee",
            image: require('../assets/vegetables/COFFE.png'),
            batonical : "Coffea arabica\n",
            nutrients : " macronutrients, fat, carbohydrate and protein .\n",
            soil : "deep,sandy loam\n",
            water : "1 to 2 L of water per plant.\n",
            temp : "64 to 70 F\n",
            mois : "50%\n",
            practical : "6 feet tall\n",
        },
        {
            id: "51",
            name: "Silver nerve plant",
            image: require('../assets/vegetables/SILVER_NERVE_PLANT.png'),
            batonical : "Sanicula europaea\n",
            nutrients : " rich in organic matter\n",
            soil : "fertile soil\n",
            water : "1 inch of water per week\n",
            temp : "70 F\n",
            mois : "18%\n",
            practical : "15 cm\n",
        },
        {
            id: "52",
            name: "Fiber Optic Grass Plant",
            image: require('../assets/vegetables/FIBER_OPTIC_GRASS.png'),
            batonical : "Oryzopsis asiatica\n",
            nutrients : "calcium, potassium,nitrogen\n",
            soil : "loamy sil\n",
            water : "0.5 inches of water per week in\n",
            temp : "80 F\n",
            mois : "70%\n",
            practical : "22 inches\n",
        },{
            id: "53",
            name: "String of Pearls",
            image: require('../assets/vegetables/STRING_OF_PEARLS.png'),
            batonical : "Senecio rowleyanus\n",
            nutrients : "phosphorous,nitrogen\n",
            soil : "sandy \n",
            water : "1 inch once every two weeks\n",
            temp : "70 F\n",
            mois : "34%\n",
            practical : "1 to 2 feet\n",
        },{
            id: "54",
            name: "Chinese Money Plant",
            image: require('../assets/vegetables/CHINESE_MONEY.png'),
            batonical : "Pilea peperomioides\n",
            nutrients : "nitrogen,phosphorous,potassium\n",
            soil : "acidic soil \n",
            water : "1/4 to 1/2 inch of water per week\n",
            temp : "13 to 30 C\n",
            mois : "57%\n",
            practical : "12 inches\n",
        },
        {
            id: "55",
            name: "Air Plant",
            image: require('../assets/vegetables/AIR_PLANT.png'),
            batonical : "Tillandsia\n",
            nutrients : "nitrogen,poyassium,phosphorous\n",
            soil : "light loamy soil\n",
            water : "1 to 2 inch once per week \n",
            temp : "50 TO 90 F\n",
            mois : "67%\n",
            practical : "",
        },
        {
            id: "56",
            name: "Rubber Plant",
            image: require('../assets/vegetables/RUBBER_PLANT.png'),
            batonical : "Ficus elastica\n",
            nutrients : "calcium, valine, isoleucine, phenylalanine and tyrosine.\n",
            soil : "peat \n",
            water : "1 inch of water per week\n",
            temp : "75 TO 80 F\n",
            mois : "47%\n",
            practical : "6 to 10 feet\n",
        },
        {
            id: "57",
            name: "ZZ Plant",
            image: require('../assets/vegetables/ZZ_PLANT.png'),
            batonical : "Zamioculcas zamiifolia\n",
            nutrients : " iron, zinc, manganese, copper, boron, molybdenum, and chlorine.\n",
            soil : "clay loamy\n",
            water : "1 -2 inches every 2-3 weeks\n",
            temp : "76 TO 90 F\n",
            mois : "50%\n",
            practical : "3 to 4 feet\n",
        },
        {
            id: "58",
            name: "English Ivy",
            image: require('../assets/vegetables/ENGLISH_IVY.png'),
            batonical : "Hedera helix\n",
            nutrients : " saponins and flavonoids\n",
            soil : "silt\nc",
            water : "1 to 1.5 inches of water per week\n",
            temp : "65 TO 85 F\n",
            mois : "22%\n",
            practical : "8 inches\n",
        },
        {
            id: "59",
            name: "Aglaonema",
            image: require('../assets/vegetables/AGLAONEMA.png'),
            batonical : "Aglaonema modestum\n",
            nutrients : "abaility to filter air from toxins and poision\n",
            soil : "organic \n",
            water : "1-2 inches of water per week \n",
            temp : "70 TO 85 F\n",
            mois : "98%\n",
            practical : "8 to 10 inches\n",
        },
        {
            id: "60",
            name: "Weeping Fig",
            image: require('../assets/vegetables/WEEPING_FIG.png'),
            batonical : "Ficus benjamina\n",
            nutrients : "fat,cholestrol,protein,carbohydrates,sugar\n",
            soil : "fertile\n",
            water : "1 inch of water per week\n",
            temp : "75 TO 85 F\n",
            mois : "87%\n",
            practical : "2 to 3 inches\n",
        },
        {
            id: "61",
            name: "Philodendron",
            image: require('../assets/vegetables/PHILODENDRON.png'),
            batonical : "Philodendron sp\n",
            nutrients : "nitrigen,potassium,phosphorous\n",
            soil : "peat fertile\n",
            water : "1 inch of water per week \n",
            temp : "75 TO 85 F\n",
            mois : "56%\n",
            practical : "3 feet\n",
        },
        {
            id: "62",
            name: "Fiddle Leaf Fig",
            image: require('../assets/vegetables/FIDDLE__LEAF_FIG.png'),
            batonical : "Ficus lyrata\n",
            nutrients : "(3% nitrogen, 1% phosphorus, 2% potassium).\n",
            soil : "well drained\n",
            water : "a cup per two feet\n",
            temp : "60 TO 80 F\n",
            mois : "78%\n",
            practical : "15 meter\n",
        },{
            id: "63",
            name: "Cast Iron Plant",
            image: require('../assets/vegetables/cast_iron_plant.png'),
            batonical : "Aspidistra elatior\n",
            nutrients : " potent air purifiers \n",
            soil : "fertiled drauned\n",
            water : "1 inch of water per week\n",
            temp : "60 TO 75 F\n",
            mois : "12%\n",
            practical : "2 to 3 feet\n",
        },{
            id: "64",
            name: "Swiss Cheese Plant",
            image: require('../assets/vegetables/swiss_cheese_plant.png'),
            batonical : "Monstera deliciosa\n",
            nutrients : "cholestrol,sodium,carbohydrate\n",
            soil : "deep sandy loam\n",
            water : "1 inch of water per week\n",
            temp : "5 TO 10 C\n",
            mois : "67%\n",
            practical : "2m\n",
        },
        {
            id: "65",
            name: "Dragon Tree",
            image: require('../assets/vegetables/DRAGON_TREE.png'),
            batonical : "Dracaena draco\n",
            nutrients : "antioxidants like flavonoids, phenolic acid, and betacyanin.\n",
            soil : "well draining potting mix\n",
            water : "1 inch once a week\n",
            temp : "90 TO 93 F\n",
            mois : "88%\n",
            practical : "20 feet\n",
        },
        {
            id: "66",
            name: "African Violets",
            image: require('../assets/vegetables/africanvoilets-1.png'),
            batonical : "Saintpaulia ionantha\n",
            nutrients : "nitrigen,potassium,phosphorous\n",
            soil : "loose organic\n",
            water : "1-2 inch of water per week\n",
            temp : "65 TO 80 F\n",
            mois : "87%\n",
            practical : "6 to 8 inches\n",
        },
        {
            id: "67",
            name: "Banyan",
            image: require('../assets/vegetables/banyan-1.png'),
            batonical : "Ficus benghalensis\n",
            nutrients : "B Sitoster, esters, glycosides, leukocyanidin, quercetin, sterols and friedelin.\n",
            soil : "well drained\n",
            water : "10 gallons of water per sq. ft. per week\n",
            temp : "10 TO 18\n",
            mois : "",
            practical : "9 inches\n",
        },
        {
            id: "68",
            name: "Oak",
            image: require('../assets/vegetables/oak-1.png'),
            batonical : "Quercus\n",
            nutrients : "Vitamin B6,fat,copper\n",
            soil : "fertiled but loose\n",
            water : "10-15 gallons weekly\n",
            temp : "45 F\n",
            mois : "36%\n",
            practical : "70 feet\n",
        },
        {
            id: "69",
            name: "Maple",
            image: require('../assets/vegetables/MAPLE01.png'),
            batonical : "Acer\n",
            nutrients : "znic,copper,calcium,iron\n",
            soil : "loamy\n",
            water : "11 gallons of water a week\n",
            temp : "MINUS 60 F\n",
            mois : "47%\n",
            practical : "10 to 45 m\n",
        },
        {
            id: "70",
            name: "Cedar",
            image: require('../assets/vegetables/CEDAR.png'),
            batonical : "Cedrus deodara\n",
            nutrients : "nitrogen,calcium,magnesium,copper,sulphur,znic\n",
            soil : "sandy\n",
            water : "1 -1 ½ inches of water each week\n",
            temp : "25 C\n",
            mois : "46%\n",
            practical : "3 to 6 m\n",
        },
        {
            id: "71",
            name: "Coconut Tree",
            image: require('../assets/vegetables/COCONUT_TREE.png'),
            batonical : "Coconut Tree\n",
            nutrients : "magnesium,phosphorous,iron\n",
            soil : "well drained loose\n",
            water : "1 and 3 inches of water per week.\n",
            temp : "20 TO 32 F\n",
            mois : "58%\n",
            practical : "30 to 45 m",
        },
        {
            id: "72",
            name: "Pine",
            image: require('../assets/vegetables/pine.png'),
            batonical : "Pinus spp\n",
            nutrients : "magnesium,iron,anti oxidants,protein\n",
            soil : "peat likesandy fertiled\n",
            water : "1 inch of water each week\n",
            temp : "28 TO 88 F\n",
            mois : "79%\n",
            practical : "3 to 80 m\n",
        },{
            id: "73",
            name: "Neem Tree",
            image: require('../assets/vegetables/neem_tree.png'),
            batonical : "Azadirachta indica\n",
            nutrients : " protein (7.1%), carbohydrates (22.9%), minerals, calcium, phosphorus, vitamin C, carotene\n",
            soil : "loose organic\n",
            water : "0.8 cups of water every 12 days\n",
            temp : "67 F\n",
            mois : "87%\n",
            practical : "30 m\n",
        },{
            id: "74",
            name: "Ash",
            image: require('../assets/vegetables/ash_plants.png'),
            batonical : "Fraxinus excelsior\n",
            nutrients : "nitrogen,potassium,phosphorous,calcium\n",
            soil : "loamy \n",
            water : "1 inch of water per week\n",
            temp : "9.5 TO 37 C\n",
            mois : "12%\n",
            practical : "2 mm\n",
        },
        {
            id: "75",
            name: "Teak\n",
            image: require('../assets/vegetables/teak.png'),
            batonical : "Tectona grandis\n",
            nutrients : "protein,fat,carbohydrate\n",
            soil : "clay loamy\n",
            water : "1-2 inches of water per week\n",
            temp : "80 F\n",
            mois : "45%\n",
            practical : "2 m\n",
        },
        {
            id: "76",
            name: "Willow\n",
            image: require('../assets/vegetables/willow.png'),
            batonical : "Salix sp\n",
            nutrients : "nitrigen,potassium,phosphorous\n",
            soil : "well drained\n",
            water : "1 inch of water per week.\n",
            temp : "17 C\n",
            mois : "67%\n",
            practical : "21 mm\n",
        },
        {
            id: "77",
            name: "Aspen\n",
            image: require('../assets/vegetables/aspen.png'),
            batonical : "Populus sp\n",
            nutrients : "Phenolic glycocides\n",
            soil : "fertile,well drained\n",
            water : " 1 to 2 inches in 1-2 weeks\n",
            temp : "61 F\n",
            mois : "89%\n",
            practical : "80 feet\n",
        },
        {
            id: "78",
            name: "Mango Tree\n",
            image: require('../assets/vegetables/mango_tree.png'),
            batonical : "Mangifera indica\n",
            nutrients : "vitamin K,riboflavin,thaimin\n",
            soil : "well drained\n",
            water : "1-2 inches of water\n",
            temp : "27 TO 36 F\n",
            mois : "90%\n",
            practical : "30 to 40 m\n",
        },
        {
            id: "79",
            name: "Birch\n",
            image: require('../assets/vegetables/birch.png'),
            batonical : "Betula pendula\n",
            nutrients : "\n",
            soil : "moist, well-drained sandy loam\n",
            water : " two to three hours a week\n",
            temp : "20 TO 30 F\n",
            mois : "78%\n",
            practical : "20 t0 40 m\n",
        },
        {
            id: "80",
            name: "Walnut Tree\n",
            image: require('../assets/vegetables/walnut.png'),
            batonical : "Juglans regia\n",
            nutrients : "vitamin B6,E, copper\n",
            soil : "loamy\n",
            water : "1 inch of water per week\n",
            temp : "40 C\n",
            mois : "77%\n",
            practical : "15 to 18 m\n",
        },
        {
            id: "81",
            name: "Alder\n",
            image: require('../assets/vegetables/alder.png'),
            batonical : "Alnus glutinosa\n",
            nutrients : "potassium,calcium,magnesium\n",
            soil : "sandy fertiled soil\n",
            water : " 0.8 cups of water every 9 days\n",
            temp : "90 F\n",
            mois : "47%\n",
            practical : "30 to 40 m\n",
        },
        {
            id: "82",
            name: "Apple Tree\n",
            image: require('../assets/vegetables/apple_tree.png'),
            batonical : "Malus domestica\n",
            nutrients : "Quercetin. ...\n",
            soil : "clay loamy\n",
            water : "an inch (2.5 cm.) every week\n",
            temp : "70 F\n",
            mois : "58%\n",
            practical : "28 m\n",
        },{
            id: "83",
            name: "Hazel\n",
            image: require('../assets/vegetables/hazel.png'),
            batonical : "Corylus avellana\n",
            nutrients : "vitamin B6,folate,potassium\n",
            soil : "peat   fertiled\n",
            water : "1 inch of water per week \n",
            temp : "13 TO 16 F\n",
            mois : "47%\n",
            practical : "12 m\n",
        },{
            id: "84",
            name: "Magnolia\n",
            image: require('../assets/vegetables/magnolia-1.png'),
            batonical : "Magnolia grandiflora\n",
            nutrients : "magnolol and honokiol\n",
            soil : "sandy\n",
            water : "1 inch per week, 5 gallons per sq. ft.\n",
            temp : "19 C\n",
            mois : "66%\n",
            practical : "15 foot\n",
        },
        {
            id: "85",
            name: "Tamarind Tree\n",
            image: require('../assets/vegetables/tamarind_tree.png'),
            batonical : "Tamarindus indica\n",
            nutrients : "vitamin B1,B3,Potassium,iron\n",
            soil : "loamy\n",
            water : " 20 gallons per week\n",
            temp : "36 TO 47.5 C\n",
            mois : "57%\n",
            practical : "24 m\n",
        },
        {
            id: "86",
            name: "Roses\n",
            image: require('../assets/vegetables/rose-1.png'),
            batonical : "Rosa\n",
            nutrients : "0.4g of ash, 70.4g of carbohydrate, 0.5 g of protein, 0.2g of fat,1.2g of crude fibre, 0.2mg of Vitamin C, 3.7mg of Iron and 120mg of Calcium\n",
            soil : "loam soil\n",
            water : "1-2 inches per week\n",
            temp : "60 t0 70 C\n",
            mois : "85%\n",
            practical : "7 inch\n",
        },
        {
            id: "87",
            name: "Aster\n",
            image: require('../assets/vegetables/aster.png'),
            batonical : "Aster\n",
            nutrients : "calcium, phosphorus, iron, and potassium\n",
            soil : "well-drained, loamy soil\n",
            water : "1 inch of water per week\n",
            temp : "20 TO 300 C\n",
            mois : "9.90%\n",
            practical : "1to  6 feet\n",
        },
        {
            id: "88",
            name: "Begonia\n",
            image: require('../assets/vegetables/begonia.png'),
            batonical : "Begonia\n",
            nutrients : "nitrogen,potassium,phosphorous,calcium\n",
            soil : " sandy loam soil.\n",
            water : "1-2 inches of  per week\n",
            temp : "72%\n",
            mois : "70 to 90%\n",
            practical : "1 foot \n",
        },
        {
            id: "89",
            name: "Peony\n",
            image: require('../assets/vegetables/peony-1.png'),
            batonical : "Paeonia\n",
            nutrients : "sugar,anti oxidants\n",
            soil : "well-drained, slightly acidic soil (6.5-7.0 pH). \n",
            water : "1 inch of water per week \n",
            temp : "32 F\n",
            mois : "3%\n",
            practical : "3 foot\n",
        },
        {
            id: "90",
            name: "Yarrow\n",
            image: require('../assets/vegetables/yarrow.png'),
            batonical : "Achillea millefolium\n",
            nutrients : "vitamins A and C, potassium, zinc, magnesium, calcium, phosphorus, and niacin\n",
            soil : "well-drained soil\n",
            water : "1 inch of water per week \n",
            temp : "65 TO 57 F\n",
            mois : "60%\n",
            practical : "3 foot\n",
        },
        {
            id: "91",
            name: "Clematis\n",
            image: require('../assets/vegetables/clematis.png'),
            batonical : "Clematis vitalba\n",
            nutrients : "nitrogen\n",
            soil : "deep, fertile, moist but well-drained soil. \n",
            water : "1-2 inches of water per week\n",
            temp : "45 F\n",
            mois : "12%\n",
            practical : "20 to 30 feet\n",
        },
        {
            id: "92",
            name: "Sunflower\n",
            image: require('../assets/vegetables/sunflowers.png'),
            batonical : "Helianthus annuus\n",
            nutrients : "phenolic acids and flavonoids\n",
            soil : " well-drained soils.\n",
            water : "1 inch of water per week \n",
            temp : "70 TO 78 F\n",
            mois : "10%\n",
            practical : "3 to 12 inches\n",
        },{
            id: "93",
            name: "Cosmos\n",
            image: require('../assets/vegetables/cosmos.png'),
            batonical : "Cosmos bipinnatus\n",
            nutrients : "bioactive compounds such as ascorbic acid, quercetin, and chlorogenic acid\n",
            soil : "neutral to alkaline soils (pH of 7.0-7.5).\n",
            water : "an inch per week.\n",
            temp : "60 F\n",
            mois : "7%\n",
            practical : "18 to 60 inches\n",
        },{
            id: "94",
            name: "Caladium\n",
            image: require('../assets/vegetables/caladium-1.png'),
            batonical : "Caladium\n",
            nutrients : "81.59% nitrogen free extract, 1.48% crude fibre, 7.31% crude protein, 4.60% ether extract, 5.21kcal/g gross energy and 5.13% ash.\n",
            soil : "well-drained soil that's rich in organic matter,\n",
            water : "1-2 inches of water per week\n",
            temp : "50 F\n",
            mois : "6%\n",
            practical : "12 to 30 inches\n",
        },
        {
            id: "95",
            name: "Canna\n",
            image: require('../assets/vegetables/canna.png'),
            batonical : "Canna\n",
            nutrients : "fat,cholestrol,protein,carbohydrates,sugar\n",
            soil : " nearly any well-draining soil that is either neutral or slightly acidic.\n",
            water : "1-2 inches per week in 5 gallon buckets. \n",
            temp : "90 F\n",
            mois : "17%\n",
            practical : "1.5 m\n",
        },
        {
            id: "96",
            name: "Ladys Mantle\n",
            image: require('../assets/vegetables/ladysmentle.png'),
            batonical : "Alchemilla vulgaris\n",
            nutrients : "calcium ,potassium\n",
            soil : "chalky, sandy soil with a pH between 5.5 and 7.5\n",
            water : "1-2 inches of water per week\n",
            temp : "60 TO 65 F\n",
            mois : "98%\n",
            practical : "18 inch\n",
        },
        {
            id: "97",
            name: "Agapanthus\n",
            image: require('../assets/vegetables/agapantus.png'),
            batonical : "Agapanthus africanus\n",
            nutrients : "slightly higher in phosphorus than nitrogen.\n",
            soil : "sand, clay, chalk or loam within an acidic, alkaline or neutral PH balance.\n",
            water : "1 to 2 inches per week in 5 gallon/sq. ft. \n",
            temp : "55 TO 60 F\n",
            mois : "89%\n",
            practical : "45 cm\n",
        },
        {
            id: "98",
            name: "Allium\n",
            image: require('../assets/vegetables/allium.png'),
            batonical : "Allium sativum\n",
            nutrients : "B vitamins, vitamin C, folate, potassium, selenium, and manganese.\n",
            soil : "sand, loam, chalk or clay\n",
            water : "1 inch of water per week\n",
            temp : "MINUS 1 TO 0 C\n",
            mois : "7.81%\n",
            practical : "4 feet\n",
        },
    ]

    useEffect(()=>{
        setPlants(plants);
        setFilteredPlants(plants);
    },[]);


    const PlantDetail = (id,name,image,batonical,nutrients,soil,water,temp,mois,practical) => {
        navigation.navigate("Detail",{ id,name,image,batonical,nutrients,soil,water,temp,mois,practical });
    }

    const filterData = (text) => {
        if (text.length > 0) {
            let newData = plants.filter(item => {
                const itemData = `${item.name.toLowerCase()}`;
                const textData = text.toLowerCase();
                if (text.length > 0) {
                    return itemData.indexOf(textData) > -1
                }
            });
            setPlants(newData);
        }
        else {
            setPlants(filteredPlants);
        }
    };

    return (
        <View style={{flex: 1, backgroundColor: "#FBFBFB", paddingHorizontal: 20,}}>
            <View style={styles.searchbar_container}>
                <TextInput onChangeText={(val)=>{
                    filterData(val);
                }} style={styles.input} placeholder={'Search'}/>
                <Feather name="search" style={styles.search_icon}/>
            </View>
            <ScrollView vertical showsVerticalScrollIndicator={false} style={{flex: 1,}}>
                <View style={styles.box_container}>
                    {
                        plant.map((item)=>{
                            return(
                                <TouchableOpacity key={item.id} style={styles.box} onPress={() => {
                                    PlantDetail(item.id,item.name,item.image,item.batonical,item.nutrients,item.soil,item.water,item.temp,item.mois,item.practical);
                                }}>
                                    <Image source={item.image} style={styles.box_image}/>
                                    <Text style={styles.box_text}>{item.name}</Text>
                                </TouchableOpacity>
                            )
                        })
                    }
                </View>

            </ScrollView>
        </View>
    )

}

const styles = StyleSheet.create({

    searchbar_container: {
        marginTop: 50,
        // marginBottom: 20,
        position: "relative",
        paddingVertical : 8,
    },
    input: {
        width: "100%",
        backgroundColor: "#fff",
        shadowColor: "#0000000F",
        shadowOffset: {
            width: 0,
            height: 8,
        },
        shadowOpacity: 0.44,
        shadowRadius: 10,
        elevation: 16,
        fontSize: 16,
        paddingVertical: 16,
        borderRadius: 30,
        paddingHorizontal: 35,
        fontWeight: "bold",
    },
    search_icon: {
        position: "absolute",
        left: 10,
        top: 25,
        fontSize: 20,
        color: "#666",
        fontWeight: "bold",
    },
    box_container: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        flexWrap : "wrap",
        marginTop: 10,
        marginBottom : 20,
    },
    box: {
        width: "48%",
        backgroundColor: "#fff",
        borderRadius: 10,
        shadowColor: "#0000000F",
        shadowOffset: {
            width: 0,
            height: 8,
        },
        shadowOpacity: 0.44,
        shadowRadius: 10,
        elevation: 16,
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        paddingVertical: 10,
        marginTop : 10,
    },
    box_text: {
        textTransform: "uppercase",
        fontWeight: "bold",
        textAlign : "center",
    },
    box_image : {
        width : 150,
        height : 150,
        resizeMode: 'contain',
    }

})


export default Home;
